version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workflow-notifier"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bteqr70ol51k"
s3_prefix = "workflow-notifier"
region = "ap-southeast-2"
capabilities = "CAPABILITY_NAMED_IAM"
